[project]
name = "the-art-of-readable-code"
version = "0.1.0"
description = "🎼 Designing and Implementing a “Minute/Hour Counter”"
readme = "README.md"
authors = [
    { name = "cassiobotaro", email = "cassiobotaro@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[tool.uv]
package = false

[dependency-groups]
dev = [
    "ruff>=0.16.0",
    "ty>=0.0.68",
]

