name: main

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"
      - run: poetry install

      - name: Run ruff format
        run: poetry run python -m ruff format  --check .

      - name: Run ruff
        run: poetry run python -m ruff check .

      - name: Run mypy
        run: poetry run python -m mypy .
